### ISSUE TITLE
BUG: CANT OPEN TRADER STORAGE AS ADMIN

### ISSUE THREAD

**Issue by breeece** [Lightman314/LightmansCurrency#121]
### Minecraft Version

1.19.3

### Forge Version

44.1.20

### Lightman's Currency Version
![image](https://user-images.githubusercontent.com/65570699/229376638-252b62be-3e10-4b46-97fc-1bd51abf6167.png)

2.1.1.0

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

When I try to open the trader storage as admin or normal player this is what pops up in my server console.
![image](https://user-images.githubusercontent.com/65570699/229374726-8681c25d-4e05-4783-b98c-674be64f192c.png)

### To Reproduce

Put down any item that has a storage and click the storage button to put items in. Server outputs error.

### Screenshots/Logs/Crash Reports

No crash

**Comment by breeece** [comment]
Actually can't open the storage at all. Admin or not. Really want to use this mod on my server but its not workin.

**Comment by breeece** [comment]
This is all it says 
![image](https://user-images.githubusercontent.com/65570699/229376430-585f4025-a930-4fa3-b9c1-ad53e1d9a54a.png)
I'm really at a loss here, it is a dedicated server I am running separate from my minecraft install. :\ Never seen this kind of thing before.

**Comment by breeece** [comment]
I am also getting this when trying to right click a terminal


[15:26:02] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@5dcf1cd, suppressing error
java.lang.RuntimeException: Attempted to load class io/github/lightman314/lightmanscurrency/common/menus/traderstorage/TraderStorageClientTab for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.3-44.1.20.jar%2368!/:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2355!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2355!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2355!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.6.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.6.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.6.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at io.github.lightman314.lightmanscurrency.common.menus.TraderStorageMenu.<init>(TraderStorageMenu.java:87) ~[lightmanscurrency-1.19.3-2.1.1.0a.jar%23198!/:1.19.3-2.1.1.0a] {re:classloading}
        at io.github.lightman314.lightmanscurrency.common.menus.TraderStorageMenu.<init>(TraderStorageMenu.java:73) ~[lightmanscurrency-1.19.3-2.1.1.0a.jar%23198!/:1.19.3-2.1.1.0a] {re:classloading}
        at io.github.lightman314.lightmanscurrency.common.traders.TraderData$TraderStorageMenuProvider.m_7208_(TraderData.java:747) ~[lightmanscurrency-1.19.3-2.1.1.0a.jar%23198!/:1.19.3-2.1.1.0a] {re:classloading}
        at net.minecraftforge.network.NetworkHooks.openScreen(NetworkHooks.java:204) ~[forge-1.19.3-44.1.20-universal.jar%23244!/:?] {re:classloading}
        at io.github.lightman314.lightmanscurrency.common.traders.TraderData.openStorageMenu(TraderData.java:739) ~[lightmanscurrency-1.19.3-2.1.1.0a.jar%23198!/:1.19.3-2.1.1.0a] {re:classloading,pl:runtimedistcleaner:A}
        at io.github.lightman314.lightmanscurrency.common.blocks.traderblocks.templates.TraderBlockBase.m_6227_(TraderBlockBase.java:97) ~[lightmanscurrency-1.19.3-2.1.1.0a.jar%23198!/:1.19.3-2.1.1.0a] {re:classloading}
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:730) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:mixin,re:classloading,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:343) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:computing_frames,re:mixin,re:classloading,pl:mixin:APP:mixins.improvableskills.json:ServerPlayerGameModeMixin,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1056) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:mixin,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,re:classloading,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:classloading,xf:OptiFine:default}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:computing_frames,re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:773) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:756) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:750) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:735) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.19.3-20221207.122022-srg.jar%23239!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

**Comment by Lightman314** [comment]
Seems like I forgot to flag a function as client-only on the Trader Rule tab, causing it to break when loaded on a dedicated server. I'll upload a patch for this shortly.

**Comment by Lightman314** [comment]
Fixed in v2.1.1.0b

**Comment by breeece** [comment]
Thank the mod gods

**Comment by breeece** [comment]
For some reason now I am seeing all the chests thru the walls. Would this have anything to do with the changes made? 
![2023-04-02_18 21 36](https://user-images.githubusercontent.com/65570699/229384498-e59110bb-34a6-423c-afda-820c605c1c25.png)

**Comment by Lightman314** [comment]
Nope. That would be an error with your rendering. Some mods that fiddle with rendering (such as optifine, flywheel, etc.) have been known to cause such issues, but usually rebooting the game will fix these.

**Comment by breeece** [comment]
Turned off fast render, all good now :D thank you!

**Comment by breeece** [comment]
Still have to setup the configs and all that good stuff.
