### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by bryanmeadows** [Lightman314/LightmansCurrency#134]
### Minecraft Version

*edited* 1.20.1

### Forge Version

47.1.0

### Lightman's Currency Version

1.20.1-2.1.2.0

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

Lootr

### Describe the bug

Sever crashed when opening a chest. Also, this is for 1.20.1, not 1.19.4, but could not choose the latest version. Here is the crash details.

at io.github.lightman314.lightmanscurrency.LightmansCurrency.LogError(LightmansCurrency.java:309) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.GetRandomChestLoot(LootManager.java:631) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.glm.CoinsInChestsModifier.apply(CoinsInChestsModifier.java:40) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.0-universal.jar%23550!/:?]

	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23545!/:?]

	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23545!/:?]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.safelyGetResults(LootManager.java:640) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.GetRandomChestLoot(LootManager.java:604) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.glm.CoinsInChestsModifier.apply(CoinsInChestsModifier.java:40) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.0-universal.jar%23550!/:?]

	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23545!/:?]

	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23545!/:?]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.safelyGetResults(LootManager.java:640) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.GetRandomChestLoot(LootManager.java:604) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.glm.CoinsInChestsModifier.apply(CoinsInChestsModifier.java:40) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.0-universal.jar%23550!/:?]

	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23545!/:?]

	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23545!/:?]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.safelyGetResults(LootManager.java:640) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.GetRandomChestLoot(LootManager.java:604) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.glm.CoinsInChestsModifier.apply(CoinsInChestsModifier.java:40) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

### To Reproduce

Loot a Lootr chest

### Screenshots/Logs/Crash Reports

at io.github.lightman314.lightmanscurrency.LightmansCurrency.LogError(LightmansCurrency.java:309) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.GetRandomChestLoot(LootManager.java:631) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.glm.CoinsInChestsModifier.apply(CoinsInChestsModifier.java:40) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.0-universal.jar%23550!/:?]

	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23545!/:?]

	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23545!/:?]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.safelyGetResults(LootManager.java:640) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.GetRandomChestLoot(LootManager.java:604) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.glm.CoinsInChestsModifier.apply(CoinsInChestsModifier.java:40) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.0-universal.jar%23550!/:?]

	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23545!/:?]

	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23545!/:?]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.safelyGetResults(LootManager.java:640) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.GetRandomChestLoot(LootManager.java:604) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.glm.CoinsInChestsModifier.apply(CoinsInChestsModifier.java:40) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.1.0-universal.jar%23550!/:?]

	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23545!/:?]

	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23545!/:?]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.safelyGetResults(LootManager.java:640) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.LootManager.GetRandomChestLoot(LootManager.java:604) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

	at io.github.lightman314.lightmanscurrency.common.loot.glm.CoinsInChestsModifier.apply(CoinsInChestsModifier.java:40) ~[lightmanscurrency-1.20.1-2.1.2.0.jar%23448!/:1.20.1-2.1.2.0]

**Comment by Lightman314** [comment]
Please attach the crash report file that was generated in the crash-report folder, as the error you copy/pasted is not complete. It tells me *where* the error occurred at, but not what error/exception actually happened.

**Comment by Lightman314** [comment]
Fixed in v2.1.2.0a

**Comment by bryanmeadows** [comment]
Sorry, I'll include the crash report next time!
