### ISSUE TITLE
BUG: Crash when typing unicode on the dicount list

### ISSUE THREAD

**Issue by zecheki** [Lightman314/LightmansCurrency#149]
### Minecraft Version

1.20.1

### Forge Version

47.2.1

### Lightman's Currency Version

2.1.2.4

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

If you click the discount list in the trader and input unicode(e.g. korean), it crashes.
Until server rebooting, you cannot reconnect.
When server reboot and you move to the trader, it is re-initialized.

### To Reproduce

1. Interact with any your trader.
2. Go to discount menu.
3. Type some unicode words and confirm.

### Screenshots/Logs/Crash Reports

1. When cofrim the dicount list with unicode. (client's log)
[12:24:30] [Render thread/ERROR]: ########## GL ERROR ##########
[12:24:30] [Render thread/ERROR]: @ Render

2. When trying to reconnect before server reboot. (client's log)
[12:24:30] [Render thread/ERROR]: 65539: Invalid mouse button 99
[12:27:05] [Render thread/ERROR]: ########## GL ERROR ##########
[12:27:05] [Render thread/ERROR]: @ Render
[12:27:05] [Render thread/ERROR]: 65539: Invalid mouse button 99
[12:27:08] [Render thread/ERROR]: ########## GL ERROR ##########
[12:27:08] [Render thread/ERROR]: @ Render
[12:27:08] [Render thread/ERROR]: 65539: Invalid mouse button 99
[12:27:16] [Render thread/ERROR]: ########## GL ERROR ##########
[12:27:16] [Render thread/ERROR]: @ Render
[12:27:16] [Render thread/ERROR]: 65539: Invalid mouse button 99
[12:27:22] [Render thread/ERROR]: ########## GL ERROR ##########
[12:27:22] [Render thread/ERROR]: @ Render
[12:27:22] [Render thread/ERROR]: 65539: Invalid mouse button 99
[12:27:32] [Render thread/ERROR]: ########## GL ERROR ##########
[12:27:32] [Render thread/ERROR]: @ Render
[12:27:32] [Render thread/ERROR]: 65539: Invalid mouse button 99

3. When trying to reconnect before server reboot. (sever's log)
[Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "io.github.lightman314.lightmanscurrency.common.player.PlayerReference.save()" because "playerReference" is null
	Index: 23
	Listeners:
		0: HIGHEST
		1: ASM: class com.github.ewan_selkirk.dimensionviewer.PlayerListHandler onPlayerConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		2: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@4519becf
		3: HIGH
		4: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		5: NORMAL
		6: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@6d02216
		7: ASM: class de.markusbordihn.adaptiveperformancetweakscore.server.ServerManager handlePlayerLoggedInEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		8: ASM: class com.tarinoita.solsweetpotato.tracking.benefits.BenefitsHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		9: ASM: class com.tarinoita.solsweetpotato.ConfigHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		10: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@5f01b727
		11: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@8accc23
		12: ASM: de.erdbeerbaerlp.dcintegration.forge.DiscordIntegrationMod@2308367d playerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		13: ASM: class tictim.paraglider.forge.event.ParagliderEventHandler onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		14: ASM: class dev.xkmc.l2library.init.events.EffectSyncEvents onServerPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		15: ASM: class dev.xkmc.l2library.init.events.BaseCapabilityEvents onServerPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		16: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@4be43f
		17: ASM: class com.logprot.event.EventHandler onEntityAdded(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		18: ASM: io.github.lightman314.lightmanscurrency.LightmansCurrency@6d6a3b1c onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		19: ASM: net.minecraftforge.common.ForgeInternalHandler@5415ec78 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		20: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@70cb6b2
		21: ASM: class com.ldtteam.structurize.event.EventSubscriber onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		22: ASM: class com.ldtteam.structurize.storage.rendering.ServerPreviewDistributor onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		23: ASM: class io.github.lightman314.lightmanscurrency.common.traders.TraderSaveData onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		24: ASM: class io.github.lightman314.lightmanscurrency.common.teams.TeamSaveData OnPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		25: ASM: class io.github.lightman314.lightmanscurrency.common.taxes.TaxSaveData onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		26: ASM: class com.mlib.contexts.OnPlayerLogged onPlayerLogged(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		27: ASM: class io.github.lightman314.lightmanscurrency.common.notifications.NotificationSaveData OnPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		28: ASM: class io.github.lightman314.lightmanscurrency.common.money.MoneyUtil onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		29: ASM: class io.github.lightman314.lightmanscurrency.common.emergency_ejection.EjectionSaveData onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		30: ASM: class io.github.lightman314.lightmanscurrency.common.blockentity.AuctionStandBlockEntity playerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		31: ASM: class io.github.lightman314.lightmanscurrency.common.bank.BankSaveData OnPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		32: ASM: class io.github.lightman314.lightmanscurrency.common.atm.ATMData onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		33: ASM: class io.github.lightman314.lightmanscurrency.common.EventHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		34: ASM: class net.combatroll.forge.ForgeEvents onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		35: ASM: class net.bettercombat.forge.events.ForgeEvents onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		36: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		37: ASM: class dev.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		38: ASM: class com.github.alexthe666.alexsmobs.event.ServerEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		39: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@556691fb
		40: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@3bc582a0
		41: ASM: com.mrcrayfish.framework.event.ForgeEvents@7b7ff4fa onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		42: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@64f0f3fb
		43: ASM: cn.mcmod_mmf.mmlib.Main@3119fd57 welcomeUsing(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		44: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@6ab60f1
		45: ASM: class net.mehvahdjukaar.moonlight.forge.MoonlightForge onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		46: ASM: class com.minecolonies.coremod.event.EventHandler onPlayerEnterWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		47: ASM: class com.minecolonies.coremod.event.FMLEventHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		48: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@6723d096
		49: ASM: class com.blamejared.crafttweaker.impl.event.CTCommonEventHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		50: ASM: class com.railwayteam.railways.forge.events.CommonEventsForge onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		51: ASM: class com.simibubi.create.foundation.events.CommonEvents playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		52: ASM: class com.simibubi.create.content.equipment.extendoGrip.ExtendoGripItem addReachToJoiningPlayersHoldingExtendo(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		53: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@70e49e50
		54: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@1368c49c
		55: ASM: mekanism.common.CommonPlayerTracker@3d5f1492 onPlayerLoginEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		56: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@59d8057 playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		57: ASM: journeymap.common.events.forge.ForgeServerEvents@35404672 onPlayerLoggedInEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		58: LOWEST
		59: net.minecraftforge.eventbus.EventBus$$Lambda$1570/0x0000000801364000@4e1982e8
java.lang.NullPointerException: Cannot invoke "io.github.lightman314.lightmanscurrency.common.player.PlayerReference.save()" because "playerReference" is null
	at TRANSFORMER/lightmanscurrency@1.20.1-2.1.2.4/io.github.lightman314.lightmanscurrency.common.traders.rules.types.PlayerDiscounts.saveAdditional(PlayerDiscounts.java:86)
	at TRANSFORMER/lightmanscurrency@1.20.1-2.1.2.4/io.github.lightman314.lightmanscurrency.common.traders.rules.TradeRule.save(TradeRule.java:69)
	at TRANSFORMER/lightmanscurrency@1.20.1-2.1.2.4/io.github.lightman314.lightmanscurrency.common.traders.rules.TradeRule.saveRules(TradeRule.java:100)
	at TRANSFORMER/lightmanscurrency@1.20.1-2.1.2.4/io.github.lightman314.lightmanscurrency.common.traders.TraderData.saveRules(TraderData.java:625)
	at TRANSFORMER/lightmanscurrency@1.20.1-2.1.2.4/io.github.lightman314.lightmanscurrency.common.traders.TraderData.save(TraderData.java:571)
	at TRANSFORMER/lightmanscurrency@1.20.1-2.1.2.4/io.github.lightman314.lightmanscurrency.common.traders.TraderSaveData.lambda$onPlayerLogin$10(TraderSaveData.java:684)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at TRANSFORMER/lightmanscurrency@1.20.1-2.1.2.4/io.github.lightman314.lightmanscurrency.common.traders.TraderSaveData.onPlayerLogin(TraderSaveData.java:684)
	at TRANSFORMER/lightmanscurrency@1.20.1-2.1.2.4/io.github.lightman314.lightmanscurrency.common.traders.__TraderSaveData_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.1/net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:875)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:261)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)

[1210월2023 12:26:30.662] [Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world

4. When moving to the trader after server reboot. (server's log)
[Server thread/WARN] [io.github.lightman314.lightmanscurrency.LightmansCurrency/]: Trader Data for block at 20589,78,17780 had to be re-initialized on interaction.

**Comment by Lightman314** [comment]
Should be fixed in v2.1.2.4a
