### ISSUE TITLE
BUG: On death with a grave mod, error

### ISSUE THREAD

**Issue by zontreck** [Lightman314/LightmansCurrency#158]
### Minecraft Version

1.20.1

### Forge Version

47.2.18

### Lightman's Currency Version

2.2.0.0b

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

Corail Tombstone
Simply Graves

### Describe the bug

When dying or using the /kill command, no grave is created if a wallet was in the curios slot. Error appears in the log.

### To Reproduce

1. Give wallet to self
2. Be using a grave mod
3. Put wallet in curio slot
4. Die

### Screenshots/Logs/Crash Reports

[21Dec2023 21:20:12.076] [Server thread/ERROR] [net.minecraft.commands.Commands/]: Command exception: /kill
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "list" is null
        at io.github.lightman314.lightmanscurrency.common.EventHandler.turnIntoEntities(EventHandler.java:275) ~[lightmanscurrency-1.20.1-2.2.0.0b.jar%23308!/:1.20.1-2.2.0.0b]
        at io.github.lightman314.lightmanscurrency.common.EventHandler.playerDrops(EventHandler.java:266) ~[lightmanscurrency-1.20.1-2.2.0.0b.jar%23308!/:1.20.1-2.2.0.0b]
        at io.github.lightman314.lightmanscurrency.common.__EventHandler_playerDrops_LivingDropsEvent.invoke(.dynamic) ~[lightmanscurrency-1.20.1-2.2.0.0b.jar%23308!/:1.20.1-2.2.0.0b]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
        at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:308) ~[forge-1.20.1-47.2.18-universal.jar%23380!/:?]
        at net.minecraft.world.entity.LivingEntity.m_6668_(LivingEntity.java:1376) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.server.level.ServerPlayer.m_6667_(ServerPlayer.java:606) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1182) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.world.entity.player.Player.m_6469_(Player.java:840) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.server.level.ServerPlayer.m_6469_(ServerPlayer.java:695) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.world.entity.LivingEntity.m_6074_(LivingEntity.java:261) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.server.commands.KillCommand.m_137813_(KillCommand.java:32) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.server.commands.KillCommand.m_137816_(KillCommand.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar%2376!/:?]
        at net.minecraft.commands.Commands.m_242674_(Commands.java:257) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1246) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_244885_(ServerGamePacketListenerImpl.java:1223) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:67) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23375!/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by Lightman314** [comment]
Fixed in v2.2.0.0c. Thank you for reporting!
