### ISSUE TITLE
BUG: CRASH WHEN CREATE AUCTION

### ISSUE THREAD

**Issue by mlus-asuka** [Lightman314/LightmansCurrency#169]
### Minecraft Version

1.20.1

### Forge Version

47.1.2

### Lightman's Currency Version

2.2.0.0g

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

CRASH WHEN CREATE AUCTION

### To Reproduce

create auction

### Screenshots/Logs/Crash Reports

Time: 2024-01-14 18:07:33
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "io.github.lightman314.lightmanscurrency.api.money.value.MoneyValue.save()" because "this.minBidDifference" is null
	at io.github.lightman314.lightmanscurrency.common.traders.auction.tradedata.AuctionTradeData.getAsNBT(AuctionTradeData.java:300) ~[lightmanscurrency-1.20.1-2.2.0.0g.jar%23408!/:1.20.1-2.2.0.0g] {re:classloading}
	at io.github.lightman314.lightmanscurrency.common.menus.traderstorage.auction.AuctionCreateTab.createAuction(AuctionCreateTab.java:77) ~[lightmanscurrency-1.20.1-2.2.0.0g.jar%23408!/:1.20.1-2.2.0.0g] {re:classloading}
	at io.github.lightman314.lightmanscurrency.client.gui.screen.inventory.traderstorage.auction.AuctionCreateClientTab.submitAuction(AuctionCreateClientTab.java:198) ~[lightmanscurrency-1.20.1-2.2.0.0g.jar%23408!/:1.20.1-2.2.0.0g] {re:classloading}
	at io.github.lightman314.lightmanscurrency.client.gui.screen.inventory.traderstorage.auction.AuctionCreateClientTab.lambda$initialize$4(AuctionCreateClientTab.java:98) ~[lightmanscurrency-1.20.1-2.2.0.0g.jar%23408!/:1.20.1-2.2.0.0g] {re:classloading}
	at io.github.lightman314.lightmanscurrency.client.gui.widget.easy.EasyButton.onPress(EasyButton.java:59) ~[lightmanscurrency-1.20.1-2.2.0.0g.jar%23408!/:1.20.1-2.2.0.0g] {re:classloading}
	at io.github.lightman314.lightmanscurrency.client.gui.widget.easy.EasyButton.m_5716_(EasyButton.java:42) ~[lightmanscurrency-1.20.1-2.2.0.0g.jar%23408!/:1.20.1-2.2.0.0g] {re:classloading}
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:175) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:38) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6375_(AbstractContainerScreen.java:276) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.ipnext.json:MixinAbstractContainerScreen,pl:mixin:APP:puzzlesapi.common.mixins.json:iteminteractions.client.AbstractContainerScreenMixin,pl:mixin:APP:puzzlesapi.common.mixins.json:iteminteractions.client.accessor.AbstractContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at io.github.lightman314.lightmanscurrency.client.gui.easy.EasyMenuScreen.m_6375_(EasyMenuScreen.java:228) ~[lightmanscurrency-1.20.1-2.2.0.0g.jar%23408!/:1.20.1-2.2.0.0g] {re:classloading}
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinMouseHandler,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:supplementaries-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:puzzlesapi.common.mixins.json:slotcycling.client.accessor.MouseHandlerAccessor,pl:mixin:APP:epicfight.mixins.json:MixinMouseHandler,pl:mixin:APP:rubidium_extras.mixins.json:Zoom.MouseMixin,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:APP:zergatul.freecam.mixin.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinScreen,pl:mixin:APP:kubejs-common.mixins.json:ScreenMixin,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:reterraforged-common.mixins.json:ScreenInvoker,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinMouseHandler,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:supplementaries-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:puzzlesapi.common.mixins.json:slotcycling.client.accessor.MouseHandlerAccessor,pl:mixin:APP:epicfight.mixins.json:MixinMouseHandler,pl:mixin:APP:rubidium_extras.mixins.json:Zoom.MouseMixin,pl:mixin:APP:creativecore.mixins.json:MouseHandlerAccessor,pl:mixin:APP:zergatul.freecam.mixin.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23438!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinMouseHandler,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMouseHandler,pl:mixin:APP:supplementaries-

**Comment by Lightman314** [comment]
Will be fixed in the next update. Thank you for reporting!

**Comment by Lightman314** [comment]
Fixed in v2.2.0.1
