### ISSUE TITLE
forge server 36.2.26

### ISSUE THREAD

**Issue by MarilynPalmer** [Lightman314/LightmansCurrency#29]
[21:38:26] [modloading-worker-5/ERROR] [io.github.lightman314.lightmanscurrency.LightmansCurrency/]: Create gamerule error
net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindMethodException: java.lang.NoSuchMethodException: net.minecraft.world.GameRules$BooleanValue.func_223571_a(boolean)
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findMethod(ObfuscationReflectionHelper.java:166) ~[forge:?]
	at io.github.lightman314.lightmanscurrency.ga
merule.ModGameRules.createBoolean(ModGameRules.java:44) ~[lightmanscurrency:1.16.4-1.0.2.6]
	at io.github.lightman314.lightmanscurrency.gamerule.ModGameRules.<clinit>(ModGameRules.java:17) ~[lightmanscurrency:1.16.4-1.0.2.6]
	at io.github.lightman314.lightmanscurrency.LightmansCurrency.doCommonStuff(LightmansCurrency.java:101) ~[lightmanscurrency:1.16.4-1.0.2.6]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:121) ~[forge:36.2]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.lang.NoSuchMethodException: net.minecraft.world.GameRules$BooleanValue.func_223571_a(boolean)
	at java.lang.Class.getDeclaredMethod(Class.java:2475) ~[?:?]
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findMethod(ObfuscationReflectionHelper.java:160) ~[forge:?]
	... 16 more
[21:38:26] [modloading-worker-5/ERROR] [io.github.lightman314.lightmanscurrency.LightmansCurrency/]: Create gamerule error
net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindMethodException: java.lang.NoSuchMethodException: net.minecraft.world.GameRules$IntegerValue.func_223562_a(int)
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findMethod(ObfuscationReflectionHelper.java:166) ~[forge:?]
	at io.github.lightman314.lightmanscurrency.gamerule.ModGameRules.createInteger(ModGameRules.java:25) ~[lightmanscurrency:1.16.4-1.0.2.6]
	at io.github.lightman314.lightmanscurrency.gamerule.ModGameRules.<clinit>(ModGameRules.java:18) ~[lightmanscurrency:1.16.4-1.0.2.6]
	at io.github.lightman314.lightmanscurrency.LightmansCurrency.doCommonStuff(LightmansCurrency.java:101) ~[lightmanscurrency:1.16.4-1.0.2.6]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:121) ~[forge:36.2]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.lang.NoSuchMethodException: net.minecraft.world.GameRules$IntegerValue.func_223562_a(int)
	at java.lang.Class.getDeclaredMethod(Class.java:2475) ~[?:?]
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findMethod(ObfuscationReflectionHelper.java:160) ~[forge:?]
	... 16 more

[debug.log](https://github.com/Lightman314/LightmansCurrency/files/7994999/debug.log)
[latest.log](https://github.com/Lightman314/LightmansCurrency/files/7995005/latest.log)

**Comment by Lightman314** [comment]
From looking at the log, it appears there is something wrong with your Minecraft installation, as the logs are showing a million file not found errors for block models & even vanilla texture files, so a missing class/function error such as this is likely an extension of that issue.

Just to be double check that forge didn't change anything though, I did launch a test server with the exact Forge & Lightman's Currency versions reported in the error, and encountered no errors of my own.
