### ISSUE TITLE
BUG: {Error Code 255}

### ISSUE THREAD

**Issue by seanis1397** [Lightman314/LightmansCurrency#56]
Minecraft Version (1,19: 
Forge Version (41.0.35): 
Lightman's Currency Version (1.19-1.1.5.1.jar): 
Other Relevant Mods & Version (LC Tech, etc.): 
Connection Type (Single-player, server/client, LAN world): Server

**Describe the bug**
When I try to set price in vending machines my game crashes, it sometimes work. When it works it sometimes bugs out Minecraft and I can't use my tools and other players become invisible to me. then I restart game and try to set price and the game crashes again. it only says sorry something is wrong and error code 255

**To Reproduce**
1. Go to vending machine
2. Click on set price

**Expected behavior**
the menu for the price for the things I want to sell should appear and I should be able to set price to anything, for example coins. 

**Screenshots/Logs/Crash Reports**
---- Minecraft Crash Report ---- CRASH REPORT
// Uh... Did I do that?

Time: 6/23/22, 6:50 PM
Description: mouseReleased event handler

java.lang.NullPointerException: Cannot invoke "io.github.lightman314.lightmanscurrency.client.gui.widget.ScrollBarWidget.onMouseReleased(double, double, int)" because "this.itemEditScroll" is null
	at io.github.lightman314.lightmanscurrency.client.gui.screen.inventory.traderstorage.item.ItemTradeEditClientTab.mouseReleased(ItemTradeEditClientTab.java:234) ~[lightmanscurrency-1.19-1.1.5.1.jar%2385!/:1.19-1.1.5.1] {re:classloading}
	at io.github.lightman314.lightmanscurrency.client.gui.screen.inventory.TraderStorageScreen.m_6348_(TraderStorageScreen.java:340) ~[lightmanscurrency-1.19-1.1.5.1.jar%2385!/:1.19-1.1.5.1] {re:classloading}
	at net.minecraft.client.MouseHandler.m_168078_(MouseHandler.java:96) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:524) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:93) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%2363!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%2351!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%2363!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:332) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1099) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.35.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.lightman314.lightmanscurrency.client.gui.screen.inventory.traderstorage.item.ItemTradeEditClientTab.mouseReleased(ItemTradeEditClientTab.java:234) ~[lightmanscurrency-1.19-1.1.5.1.jar%2385!/:1.19-1.1.5.1] {re:classloading}
	at io.github.lightman314.lightmanscurrency.client.gui.screen.inventory.TraderStorageScreen.m_6348_(TraderStorageScreen.java:340) ~[lightmanscurrency-1.19-1.1.5.1.jar%2385!/:1.19-1.1.5.1] {re:classloading}
	at net.minecraft.client.MouseHandler.m_168078_(MouseHandler.java:96) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:524) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:93) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%2363!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%2351!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%2363!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading}
-- Affected screen --
Details:
	Screen name: io.github.lightman314.lightmanscurrency.client.gui.screen.inventory.TraderStorageScreen
Stacktrace:
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:524) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:93) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%2363!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%2351!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%2363!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:332) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1099) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.35.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?] {}

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Seanjohansson'/65, l='ClientLevel', x=433.41, y=63.00, z=-473.46]]
	Chunk stats: 729, 461
	Level dimension: minecraft:overworld
	Level spawn location: World: (36,64,-415), Section: (at 4,0,1 in 2,4,-26; chunk contains blocks 32,-64,-416 to 47,319,-401), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 14204145 game time, 294310 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:448) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2169) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:678) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.19-20220607.102129-srg.jar%2393!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.35.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Mac OS X (x86_64) version 12.4
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 911695872 bytes (869 MiB) / 2464153600 bytes (2350 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Radeon Pro 580
	Graphics card #0 vendor: AMD (0x1002)
	Graphics card #0 VRAM (MB): 8192.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: Revision ID: 0x00c0, ROM Revision: 113-D000AA-931, VBIOS Version: 113-D0001A1X-025, EFI Driver Version: 01.00.931
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4 SO-DIMM
	Memory slot #1 capacity (MB): 0.00
	Memory slot #1 clockSpeed (GHz): -0.00
	Memory slot #1 type: Empty
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4 SO-DIMM
	Memory slot #3 capacity (MB): 0.00
	Memory slot #3 clockSpeed (GHz): -0.00
	Memory slot #3 type: Empty
	Virtual memory max (MB): 16384.00
	Virtual memory used (MB): 9270.84
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -Xss1M -Xmx4096m -Xms256m
	Launched Version: forge-41.0.35
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon Pro 580 OpenGL Engine GL version 4.1 ATI-4.8.54, ATI Technologies Inc.
	Window size: 5120x2880
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	ModLauncher: 10.0.1+10.0.1+main.e9521dc3
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		lightmanscurrency-1.19-1.1.5.1.jar                |Lightman's Currency           |lightmanscurrency             |1.19-1.1.5.1        |DONE      |Manifest: NOSIGNATURE
		morevillagers-forge-1.19-4.0.1.jar                |More Villagers                |morevillagers                 |4.0.1               |DONE      |Manifest: NOSIGNATURE
		Gobber2-Forge-1.19.0-2.7.1.jar                    |Gobber 2                      |gobber2                       |2.7.1               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.19-2.0.0.112.jar             |TerraBlender                  |terrablender                  |1.19-2.0.0.112      |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.19-17.0.0.136.jar                 |Biomes O' Plenty              |biomesoplenty                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		ferritecore-5.0.0-forge.jar                       |Ferrite Core                  |ferritecore                   |5.0.0               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		mcw-furniture-3.0.0-mc1.19.jar                    |Macaw's Furniture             |mcwfurnitures                 |3.0.0               |DONE      |Manifest: NOSIGNATURE
		transparent-5.1.0+1.19-forge.jar                  |Transparent                   |transparent                   |5.1.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.19-forge-11.0.0.206.jar                     |Just Enough Items             |jei                           |11.0.0.206          |DONE      |Manifest: NOSIGNATURE
		carryon-1.19-1.18.0.1.jar                         |Carry On                      |carryon                       |1.18.0.1            |DONE      |Manifest: NOSIGNATURE
		Enhanced-Farming-1.19-1.4.3.jar                   |Enhanced Farming              |enhancedfarming               |1.4.3               |DONE      |Manifest: NOSIGNATURE
		forge-1.19-41.0.35-universal.jar                  |Forge                         |forge                         |41.0.35             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Aquaculture-1.19-2.4.1.jar                        |Aquaculture 2                 |aquaculture                   |1.19-2.4.1          |DONE      |Manifest: NOSIGNATURE
		Paintings-forge-1.19-10.0.0.0.jar                 |Paintings ++                  |paintings                     |10.0.0.0            |DONE      |Manifest: NOSIGNATURE
		ecologics-forge-1.19-2.1.0.jar                    |Ecologics                     |ecologics                     |2.1.0               |DONE      |Manifest: NOSIGNATURE
		advancednetherite-1.13.1-1.19.jar                 |Advanced Netherite            |advancednetherite             |1.13.1              |DONE      |Manifest: NOSIGNATURE
		corpse-1.19-1.0.4.jar                             |Corpse                        |corpse                        |1.19-1.0.4          |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.19-8.0.1.jar                  |Traveler's Backpack           |travelersbackpack             |8.0.1               |DONE      |Manifest: NOSIGNATURE
		sit-1.19-1.3.2.jar                                |Sit                           |sit                           |1.3.2               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 823fd1e3-ddf2-4a99-9f64-86ea04f6e859
	FML: 41.0
	Forge: net.minecraftforge:41.0.35

**Additional context**
I play on an Imac

**Comment by Lightman314** [comment]
I'll make sure it gets fixed in the next update. The only potential reason for this though would be the mouse release code some running after the tab has been changed, but before the tab has been initialized (and thus before the widgets have been created). Fortunately I can just simply add some null checks and/or error catches to keep any errors from happening if it's processed out of order.

**Comment by Lightman314** [comment]
Should be fixed in v1.1.5.2
