### ISSUE TITLE
BUG: Coin Jar infinite loop when getting non-item capability.

### ISSUE THREAD

**Issue by Dhakko** [Lightman314/LightmansCurrency#93]
Minecraft Version (REQUIRED): 1.18.2
Forge Version (REQUIRED): Forge 1.18.2 - 40.1.73
Lightman's Currency Version (REQUIRED): [lightmanscurrency-1.18.2-2.0.0.2a.jar]
Other Relevant Mods & Version (LC Tech, etc.): 1.18.2 latest version mod
Connection Type (Single-player, server/client, LAN world): Server
If playing on a server, was the server ever in Offline Mode: 

**Describe the bug**
Placing the item on the ground is when the crash happens and the server restarts.

**To Reproduce**

**Expected behavior**

**Screenshots/Logs/Crash Reports**
You can find your minecraft logs in the /logs folder (ideally the latest.log file if you've not launched your game again since the error happened, and/or crash report if a crash happened)

crashing element image:
https://cdn.discordapp.com/attachments/817379720882159618/1024980483211272212/unknown.png

**Additional context**

CRASH SERVER:

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 9/29/22, 9:41 AM
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at net.minecraft.server.dedicated.ServerWatchdog.run(ServerWatchdog.java:45) [server-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at net.minecraft.server.dedicated.ServerWatchdog.run(ServerWatchdog.java:45) ~[server-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:classloading}
-- Thread Dump --
Details:
	Threads: "Reference Handler" daemon prio=10 Id=2 RUNNABLE
	at java.base@17.0.2/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
	at java.base@17.0.2/java.lang.ref.Reference.processPendingReferences(Reference.java:253)
	at java.base@17.0.2/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)

"Finalizer" daemon prio=8 Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@e8dea4c
	at java.base@17.0.2/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@e8dea4c
	at java.base@17.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@17.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	at java.base@17.0.2/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)

"Signal Dispatcher" daemon prio=9 Id=4 RUNNABLE

"Common-Cleaner" daemon prio=8 Id=12 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@4a05ed
	at java.base@17.0.2/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@4a05ed
	at java.base@17.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@17.0.2/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
	at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
	at java.base@17.0.2/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)

"Notification Thread" daemon prio=9 Id=13 RUNNABLE

"Thread-0" daemon prio=5 Id=19 TIMED_WAITING
	at java.base@17.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:376)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:190)

"FileSystemWatchService" daemon prio=5 Id=20 RUNNABLE (in native)
	at java.base@17.0.2/sun.nio.fs.LinuxWatchService.poll(Native Method)
	at java.base@17.0.2/sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314)
	at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)

"Timer hack thread" daemon prio=5 Id=30 TIMED_WAITING
	at java.base@17.0.2/java.lang.Thread.sleep(Native Method)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.Util$8.run(Util.java:628)

"DestroyJavaVM" prio=5 Id=55 RUNNABLE

"Netty Epoll Server IO #0" daemon prio=8 Id=56 RUNNABLE (in native)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.Native.epollWait(Native Method)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.Native.epollWait(Native.java:192)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.Native.epollWait(Native.java:185)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:290)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:347)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)

"FileSystemWatchService" daemon prio=8 Id=57 RUNNABLE (in native)
	at java.base@17.0.2/sun.nio.fs.LinuxWatchService.poll(Native Method)
	at java.base@17.0.2/sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314)
	at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)

"Server Watchdog" daemon prio=8 Id=61 RUNNABLE
	at java.management@17.0.2/sun.management.ThreadImpl.dumpThreads0(Native Method)
	at java.management@17.0.2/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
	at java.management@17.0.2/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.ServerWatchdog.run(ServerWatchdog.java:43)
	at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)

"pool-3-thread-1" prio=5 Id=62 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@475813c
	at java.base@17.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@475813c
	at java.base@17.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
	at java.base@17.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
	at java.base@17.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
	at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
	at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
	at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	...

"Thread-7" prio=8 Id=64 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@41770fd6
	at java.base@17.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@41770fd6
	at java.base@17.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
	at java.base@17.0.2/java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:460)
	at TRANSFORMER/plasmo_voice@1.2.19/su.plo.voice.server.socket.SocketServerUDPQueue.run(SocketServerUDPQueue.java:29)

"Thread-6" prio=8 Id=63 RUNNABLE (in native)
	at java.base@17.0.2/sun.nio.ch.DatagramChannelImpl.receive0(Native Method)
	at java.base@17.0.2/sun.nio.ch.DatagramChannelImpl.receiveIntoNativeBuffer(DatagramChannelImpl.java:750)
	at java.base@17.0.2/sun.nio.ch.DatagramChannelImpl.receive(DatagramChannelImpl.java:728)
	at java.base@17.0.2/sun.nio.ch.DatagramChannelImpl.trustedBlockingReceive(DatagramChannelImpl.java:666)
	at java.base@17.0.2/sun.nio.ch.DatagramChannelImpl.blockingReceive(DatagramChannelImpl.java:635)
	at java.base@17.0.2/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:240)
	at java.base@17.0.2/java.net.DatagramSocket.receive(DatagramSocket.java:700)
	at TRANSFORMER/plasmo_voice@1.2.19/su.plo.voice.common.packets.udp.PacketUDP.read(PacketUDP.java:82)
	...

	Number of locked synchronizers = 1
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@2049523e

"bStats-Metrics" prio=8 Id=65 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@707c4eb7
	at java.base@17.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@707c4eb7
	at java.base@17.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
	at java.base@17.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
	at java.base@17.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
	at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
	at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
	at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	...

"Java2D Disposer" daemon prio=10 Id=66 WAITING on java.lang.ref.ReferenceQueue$Lock@58a84de5
	at java.base@17.0.2/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@58a84de5
	at java.base@17.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@17.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	at java.desktop@17.0.2/sun.java2d.Disposer.run(Disposer.java:145)
	at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)

"Netty Epoll Server IO #1" daemon prio=8 Id=73 RUNNABLE (in native)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.Native.epollWait0(Native Method)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.Native.epollWait(Native.java:176)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:281)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:351)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)

"Netty Epoll Server IO #2" daemon prio=8 Id=74 RUNNABLE (in native)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.Native.epollWait0(Native Method)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.Native.epollWait(Native.java:176)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:281)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:351)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)

"pool-4-thread-1" prio=5 Id=78 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2158f099
	at java.base@17.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@2158f099
	at java.base@17.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
	at java.base@17.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
	at java.base@17.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
	at java.base@17.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
	at java.base@17.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
	at java.base@17.0.2/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
	at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
	...

Stacktrace:
	at net.minecraft.server.dedicated.ServerWatchdog.run(ServerWatchdog.java:45) [server-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

-- Performance stats --
Details:
	Random tick rate: 3
	Level stats: ResourceKey[minecraft:dimension / minecraft:overworld]: players: 0, entities: 0,0,0,0,0,0,970 [], block_entities: 477 [<null>:477], block_ticks: 0, fluid_ticks: 0, chunk_source: Chunks[S] W: 0 E: 0,0,0,0,0,0,970,
ResourceKey[minecraft:dimension / minecraft:the_nether]: players: 0, entities: 0,0,0,0,0,0,0 [], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: Chunks[S] W: 0 E: 0,0,0,0,0,0,0,
ResourceKey[minecraft:dimension / minecraft:the_end]: players: 0, entities: 0,0,0,0,0,0,0 [], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: Chunks[S] W: 0 E: 0,0,0,0,0,0,0
Stacktrace:
	at net.minecraft.server.dedicated.ServerWatchdog.run(ServerWatchdog.java:45) [server-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 4.19.0-18-amd64
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 9363227568 bytes (8929 MiB) / 18907922432 bytes (18032 MiB) up to 34359738368 bytes (32768 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 33196.08
	Virtual memory used (MB): 23035.77
	Swap memory total (MB): 1023.99
	Swap memory used (MB): 510.15
	JVM Flags: 2 total; -Xms128M -Xmx32768M
	Server Running: true
	Player Count: 0 / 100; []
	Data Packs: vanilla, mod:forge, mod:trashslot (incompatible), mod:incapacitated (incompatible), mod:nourished_end, mod:jei (incompatible), mod:galosphere (incompatible), mod:visualworkbench (incompatible), mod:graveyard (incompatible), mod:sophisticatedcore (incompatible), mod:village_employment, mod:citadel (incompatible), mod:alexsmobs (incompatible), mod:artifacts, mod:more_babies (incompatible), mod:sophisticatedbackpacks (incompatible), mod:twigs (incompatible), mod:balm (incompatible), mod:walljump (incompatible), mod:blueprint (incompatible), mod:carryon (incompatible), mod:konkrete (incompatible), mod:neapolitan (incompatible), mod:corpse (incompatible), mod:dungeons_arise, mod:chipped (incompatible), mod:farmersdelight (incompatible), mod:culturaldelights, mod:dynamic_asset_generator (incompatible), mod:excavated_variants (incompatible), mod:terrablender (incompatible), mod:ambientsounds (incompatible), mod:jade, mod:another_furniture (incompatible), mod:creativecore (incompatible), mod:flywheel (incompatible), mod:create, mod:curios (incompatible), mod:xaerominimap, mod:moreplayermodels (incompatible), mod:securitycraft (incompatible), mod:earthmobsmod, mod:framedblocks, mod:inventoryhud (incompatible), mod:blocksplus (incompatible), mod:architectury (incompatible), mod:biomemakeover (incompatible), mod:adorn (incompatible), mod:puzzleslib (incompatible), mod:byg (incompatible), mod:justzoom (incompatible), mod:expandability (incompatible), mod:geckolib3 (incompatible), mod:creeperoverhaul (incompatible), dynamic_asset_generator:data (incompatible), mod:playeranimator, mod:emotecraft (incompatible), mod:lag_removal (incompatible), mod:toolbelt, mod:appleskin (incompatible), mod:tradingpost (incompatible), mod:elevatorid, mod:plasmo_voice (incompatible), mod:quickteleports (incompatible), mod:quickhomes (incompatible), mod:quickspawns (incompatible), mod:randomtp (incompatible), mod:lightmanscurrency (incompatible), mod:mavm (incompatible)
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
		kotlinforforge@3.4.0
	Mod List: 
		trashslot-forge-1.18.1-11.0.2.jar                 |TrashSlot                     |trashslot                     |11.0.2              |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-0.1.0.jar              |Player Animator               |playeranimator                |0.1.0               |DONE      |Manifest: NOSIGNATURE
		incapacitated-1.18-1.2.2.jar                      |Incapacitated                 |incapacitated                 |1.18-1.2.2          |DONE      |Manifest: NOSIGNATURE
		Enlightened+End+BB+V1.5.jar                       |Enlightened End               |nourished_end                 |1.1.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.1.232.jar                          |Just Enough Items             |jei                           |9.7.1.232           |DONE      |Manifest: NOSIGNATURE
		Galosphere-1.18.2-1.0.4.jar                       |Galosphere                    |galosphere                    |1.18.2-1.0.4        |DONE      |Manifest: NOSIGNATURE
		VisualWorkbench-v3.3.0-1.18.2-Forge.jar           |Visual Workbench              |visualworkbench               |3.3.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		The_Graveyard_1.9.1_(FORGE)_for_1.18.2.jar        |The Graveyard                 |graveyard                     |1.9.1               |DONE      |Manifest: NOSIGNATURE
		randomtp-6.1.0+1.18-forge.jar                     |Random Teleport Mod           |randomtp                      |6.1.0+1.18          |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.18.2-0.5.1.98.jar             |Sophisticated Core            |sophisticatedcore             |1.18.2-0.5.1.98     |DONE      |Manifest: NOSIGNATURE
		village-employment-1.18.2-1.5.1.jar               |Village Employment            |village_employment            |1.5.1               |DONE      |Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.18.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.6              |DONE      |Manifest: NOSIGNATURE
		artifacts-1.18.2-4.1.0.jar                        |Artifacts                     |artifacts                     |1.18.2-4.1.0        |DONE      |Manifest: NOSIGNATURE
		quickteleports-1.18.2-1.2.0-forge.jar             |QuickTeleports                |quickteleports                |1.18.2-1.2.0        |DONE      |Manifest: NOSIGNATURE
		lightmanscurrency-1.18.2-2.0.0.2a.jar             |Lightman's Currency           |lightmanscurrency             |1.18.2-2.0.0.2a     |DONE      |Manifest: NOSIGNATURE
		More+Babies-forge-1.18.1-0.5.2.jar                |More Babies                   |more_babies                   |0.5.2               |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.2-3.18.17.680.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.18.17.680  |DONE      |Manifest: NOSIGNATURE
		twigs-forge-1.1.4-patch3+1.18.2.jar               |Twigs                         |twigs                         |1.1.4-patch1+1.18.2 |DONE      |Manifest: NOSIGNATURE
		balm-3.2.0+0.jar                                  |Balm                          |balm                          |3.2.0+0             |DONE      |Manifest: NOSIGNATURE
		walljump-forge-1.18.1-1.3.7.jar                   |Wall-Jump!                    |walljump                      |1.18.1-1.3.7        |DONE      |Manifest: NOSIGNATURE
		blueprint-1.18.2-5.4.3.jar                        |Blueprint                     |blueprint                     |5.4.3               |DONE      |Manifest: NOSIGNATURE
		carryon-1.18.2-1.17.0.8.jar                       |Carry On                      |carryon                       |1.17.0.8            |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.73-universal.jar                |Forge                         |forge                         |40.1.73             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		konkrete_forge_1.5.1_MC_1.18-1.18.2.jar           |Konkrete                      |konkrete                      |1.5.1               |DONE      |Manifest: NOSIGNATURE
		neapolitan-1.18.2-3.0.0.jar                       |Neapolitan                    |neapolitan                    |3.0.0               |DONE      |Manifest: NOSIGNATURE
		emotecraft-for-MC1.18.2-2.2.2-forge.jar           |Emotecraft                    |emotecraft                    |2.2.2               |DONE      |Manifest: NOSIGNATURE
		quickhomes-1.18.2-1.3.0-forge.jar                 |QuickHomes                    |quickhomes                    |1.18.2-1.3.0        |DONE      |Manifest: NOSIGNATURE
		corpse-1.18.2-1.0.1.jar                           |Corpse                        |corpse                        |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.18.2-2.1.50d-beta.jar             |When Dungeons Arise           |dungeons_arise                |2.1.50d-1.18.2      |DONE      |Manifest: NOSIGNATURE
		chipped-1.18.2-1.2.1-forge.jar                    |Chipped                       |chipped                       |1.18.2-1.2.1-forge  |DONE      |Manifest: NOSIGNATURE
		server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.2-1.1.2.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.1.2        |DONE      |Manifest: NOSIGNATURE
		culturaldelights-1.18.2-0.12.1.jar                |Cultural Delights             |culturaldelights              |1.18.2-0.12.1       |DONE      |Manifest: NOSIGNATURE
		dynamic_asset_generator-forge-1.18.2-0.6.3.jar    |DynamicAssetGenerator         |dynamic_asset_generator       |0.6.3               |DONE      |Manifest: NOSIGNATURE
		excavated_variants-forge-1.18.2-0.6.4.jar         |Excavated Variants            |excavated_variants            |0.6.4               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.1.0.102.jar           |TerraBlender                  |terrablender                  |1.18.2-1.1.0.102    |DONE      |Manifest: NOSIGNATURE
		lag_removal-1.1.1-1.18.jar.jar                    |lag_removal                   |lag_removal                   |1.1.1               |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.0.16_mc1.18.2.jar          |Ambient Sounds                |ambientsounds                 |5.0.16              |DONE      |Manifest: NOSIGNATURE
		ToolBelt-1.18.2-1.18.8.jar                        |Tool Belt                     |toolbelt                      |1.18.8              |DONE      |Manifest: NOSIGNATURE
		Jade-1.18.2-forge-5.2.3.jar                       |Jade                          |jade                          |5.2.3               |DONE      |Manifest: NOSIGNATURE
		plasmovoice-forge-1.18-1.2.19.jar                 |Plasmo Voice                  |plasmo_voice                  |1.2.19              |DONE      |Manifest: NOSIGNATURE
		another_furniture-forge-1.1.3-1.18.2.jar          |Another Furniture             |another_furniture             |1.1.3-1.18.2        |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.6.12_mc1.18.2.jar           |CreativeCore                  |creativecore                  |2.6.12              |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.5.jar                   |Flywheel                      |flywheel                      |0.6.5               |DONE      |Manifest: NOSIGNATURE
		create-1.18.2-0.5.0.d.jar                         |Create                        |create                        |0.5.0.d             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.13.2_Forge_1.18.2.jar           |Xaero's Minimap               |xaerominimap                  |22.13.2             |DONE      |Manifest: NOSIGNATURE
		MorePlayerModels-1.18.2.20220801.jar              |More Player Models            |moreplayermodels              |1.18.2.20220801     |DONE      |Manifest: NOSIGNATURE
		[1.18.2]+SecurityCraft+v1.9.3.1.jar               |SecurityCraft                 |securitycraft                 |1.9.3.1             |DONE      |Manifest: NOSIGNATURE
		EarthMobs-1.18.2-1.1.2.jar                        |Earth Mobs Mod                |earthmobsmod                  |1.18.2-1.1.2        |DONE      |Manifest: NOSIGNATURE
		FramedBlocks-5.6.0.jar                            |FramedBlocks                  |framedblocks                  |5.6.0               |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.18.2-1.8.4.jar                       |Elevator Mod                  |elevatorid                    |1.18.2-1.8.4        |DONE      |Manifest: NOSIGNATURE
		InventoryHud_[1.18].forge-3.4.4.jar               |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.4               |DONE      |Manifest: NOSIGNATURE
		Blocks+++1.18.1+-+1.4.jar                         |Blocks +                      |blocksplus                    |1.4                 |DONE      |Manifest: NOSIGNATURE
		architectury-4.9.83-forge.jar                     |Architectury                  |architectury                  |4.9.83              |DONE      |Manifest: NOSIGNATURE
		biomemakeover-FORGE-1.18.2-1.4.30.jar             |Biome Makeover                |biomemakeover                 |1.18.2-1.4.30       |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18.2-2.4.1.jar                |AppleSkin                     |appleskin                     |2.4.1+mc1.18.2      |DONE      |Manifest: NOSIGNATURE
		Adorn-3.5.0+1.18.2-forge.jar                      |Adorn                         |adorn                         |3.5.0+1.18.2        |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.3.5-1.18.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.3.5               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.2.jar    |Oh The Biomes You'll Go       |byg                           |1.4                 |DONE      |Manifest: NOSIGNATURE
		justzoom_forge_1.0.1_MC_1.18-1.18.1.jar           |Just Zoom                     |justzoom                      |1.0.1               |DONE      |Manifest: NOSIGNATURE
		mavm-mc1.18.2-forge-1.0.8b.jar                    |More Axolotl Variants Mod     |mavm                          |1.0.8b              |DONE      |Manifest: NOSIGNATURE
		expandability-6.0.0.jar                           |ExpandAbility                 |expandability                 |6.0.0               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.34.jar                    |GeckoLib                      |geckolib3                     |3.0.34              |DONE      |Manifest: NOSIGNATURE
		creeperoverhaul-1.18.2-1.3.0-forge.jar            |Creeper Overhaul              |creeperoverhaul               |1.3.0               |DONE      |Manifest: NOSIGNATURE
		quickspawns-1.18.2-1.0.3-forge.jar                |QuickSpawns                   |quickspawns                   |1.18.2-1.0.3        |DONE      |Manifest: NOSIGNATURE
		TradingPost-v3.2.0-1.18.2-Forge.jar               |Trading Post                  |tradingpost                   |3.2.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
	Crash Report UUID: 901011df-560e-43b5-aad7-23e6bd672b79
	FML: 40.1
	Forge: net.minecraftforge:40.1.73
	FramedBlocks BlockEntity Warning: Not applicable

**Comment by Lightman314** [comment]
Fixed in v2.0.0.2b

**Comment by Dhakko** [comment]
Thanks, the best mod developer ever, amazing support. <3
